language: node_js
node_js:
    - 10
sudo: false
install:
    - npm install -g enactjs/cli#develop
    - npm install
    - npm install --force enactjs/docs-utils#feature/test-branch

script:
    - find -E -L . -type d -regex '.*/(node_modules|build|sampler|samples|tests|coverage)' -prune -o -type f -name '*.js' -print0 | xargs -0 grep -l "@module"
    - npm run lint -- -- --max-warnings 0 .
    - npm run test
    - echo -e "\x1b\x5b35;1m*** Starting docs validation...\x1b\x5b0m"
    - npm run validate-docs
    - echo -e "\x1b\x5b35;1m*** Docs validation complete\x1b\x5b0m"
